server:
  port: 8081
#spring:
#  application:
#    name: sys
#  cloud:
#    nacos:
#      discovery:
#        #注意:使用nacos-host变量方式配置，需要在hosts文件中配置127.0.0.1 nacos-host
#        server-addr: ${nacos-host:nacos-host}:${nacos-port:8848}
#        #nacos的命名空间ID，默认是public
#        namespace:
#      config:
#        server-addr: ${spring.cloud.nacos.discovery.server-addr}
#        namespace: ${spring.cloud.nacos.discovery.namespace}
#        group: DEFAULT_GROUP
#        file-extension: yml
#  # 因为springboot 2.4版本以后默认关闭加载bootstrap.yml，所以只能通过此方式连接到nacos config
#  config:
#    import:
#      - nacos:${spring.application.name}.${spring.cloud.nacos.config.file-extension}
spring:
  # DataSource Config
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/easy_item?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: root@123
  data:
    redis:
      # Redis服务器连接地址
      host: 127.0.0.1
      # Redis服务器连接端口
      port: 6379
      # Redis服务器连接密码（默认为空）
      password: 123456
      # Redis服务器连接超时时间
      connect-timeout: 1800000
      # Redis数据库索引（默认为0）
      database: 0
      lettuce:
        pool:
          # 连接池中的最大空闲连接 默认 8
          max-idle: 8
          # 连接池中的最小空闲连接 默认 0
          min-idle: 0
          # 连接池最大连接数（使用负值表示没有限制） 默认 8
          max-active: 8
          # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
          max-wait: -1
mybatis-plus:
  configuration:
    # mybatis-plus 开启默认打印日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl