server:
  port: 8081

spring:
  application:
    name: sys
  cloud:
    nacos:
      discovery:
        #注意:使用nacos-host变量方式配置，需要在hosts文件中配置127.0.0.1 nacos-host
        server-addr: ${nacos-host:nacos-host}:${nacos-port:8848}
        #nacos的命名空间ID，默认是public
        namespace:
      config:
        server-addr: ${spring.cloud.nacos.discovery.server-addr}
        namespace: ${spring.cloud.nacos.discovery.namespace}
        group: DEFAULT_GROUP
        file-extension: yml
  # 因为springboot 2.4版本以后默认关闭加载bootstrap.yml，所以只能通过此方式连接到nacos config
  config:
    import:
      - nacos:${spring.application.name}.${spring.cloud.nacos.config.file-extension}
