server:
  port: 8101
spring:
#  application:
#    name: gateway
  cloud:
#    nacos:
#      discovery:
#        # nacos-host需在本机host文件中做映射，方便地址切换；也可直接修改成具体地址。建议使用前者，可修改一处所有服务都可以生效
#        server-addr: ${nacos-host:nacos-host}:${nacos-port:8848}
#        #nacos的命名空间ID，默认是public
#        namespace:
#    gateway:
#      discovery:
#        locator:
#          enabled: true # 启用自动根据服务ID生成路由
#          lower-case-service-id: true # 设置路由的路径为小写的服务ID

    gateway:
      routes:
        - id: sys						# 路由唯一标识
          uri: http://localhost:8081		# 路由指向目的地URL或服务名，客户端请求最终被转发到的微服务
          predicates:
            - Path=/sys/** 				# 断言：以manager开头的请求都负载到manager_server服务
          filters:
            - RewritePath=/sys/(?<segment>.*), /$\{segment} # 过滤器：过滤掉url里的manager,例如http://ip:port/manager/test -> http://ip:port/test
          order: 5						# 用于多个Route之间的排序，数值越小越靠前，匹配优先级越高
