server:
  port: 8101
spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        # nacos-host需在本机host文件中做映射，方便地址切换；也可直接修改成具体地址。建议使用前者，可修改一处所有服务都可以生效
        server-addr: ${nacos-host:nacos-host}:${nacos-port:8848}
        #nacos的命名空间ID，默认是public
        namespace:
    gateway:
      discovery:
        locator:
          enabled: true # 启用自动根据服务ID生成路由
          lower-case-service-id: true # 设置路由的路径为小写的服务ID